using System.ComponentModel;

namespace YandexMusicRPC
{
    partial class MainWindow
    {
        private IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            components = new Container();
            ComponentResourceManager resources = new ComponentResourceManager(typeof(MainWindow));
            SettingsGroup = new GroupBox();
            LargeImageDomainUpDown = new DomainUpDown();
            SmallImageDomainUpDown = new DomainUpDown();
            LargeImageLabel = new Label();
            SmallImageLabel = new Label();
            ChangeSettingsButton = new Button();
            DetailsFormatTextBox = new TextBox();
            DetailsFormatLinkLabel = new LinkLabel();
            SecondButtonDomainUpDown = new DomainUpDown();
            SecondButtonLabel = new Label();
            FirstButtonDomainUpDown = new DomainUpDown();
            FirstButtonLabel = new Label();
            RPCCheckBox = new CheckBox();
            DarkThemeCheckBox = new CheckBox();
            CaptionColorButton = new Button();
            CaptionColorDialog = new ColorDialog();
            AutoStartCheckBox = new CheckBox();
            SourceCodeLinkLabel = new LinkLabel();
            HideToTrayButton = new Button();
            TrayIcon = new NotifyIcon(components);
            TrayContextMenu = new ContextMenuStrip(components);
            openToolStripMenuItem = new ToolStripMenuItem();
            exitToolStripMenuItem = new ToolStripMenuItem();
            SettingsGroup.SuspendLayout();
            TrayContextMenu.SuspendLayout();
            SuspendLayout();
            SettingsGroup.Controls.Add(LargeImageDomainUpDown);
            SettingsGroup.Controls.Add(SmallImageDomainUpDown);
            SettingsGroup.Controls.Add(LargeImageLabel);
            SettingsGroup.Controls.Add(SmallImageLabel);
            SettingsGroup.Controls.Add(ChangeSettingsButton);
            SettingsGroup.Controls.Add(DetailsFormatTextBox);
            SettingsGroup.Controls.Add(DetailsFormatLinkLabel);
            SettingsGroup.Controls.Add(SecondButtonDomainUpDown);
            SettingsGroup.Controls.Add(SecondButtonLabel);
            SettingsGroup.Controls.Add(FirstButtonDomainUpDown);
            SettingsGroup.Controls.Add(FirstButtonLabel);
            SettingsGroup.Location = new Point(12, 59);
            SettingsGroup.Name = "SettingsGroup";
            SettingsGroup.Size = new Size(514, 150);
            SettingsGroup.TabIndex = 0;
            SettingsGroup.TabStop = false;
            SettingsGroup.Text = "Settings";
            LargeImageDomainUpDown.Items.Add("Track");
            LargeImageDomainUpDown.Items.Add("Artist");
            LargeImageDomainUpDown.Items.Add("Album [Default]");
            LargeImageDomainUpDown.Location = new Point(321, 92);
            LargeImageDomainUpDown.Name = "LargeImageDomainUpDown";
            LargeImageDomainUpDown.ReadOnly = true;
            LargeImageDomainUpDown.Size = new Size(120, 23);
            LargeImageDomainUpDown.TabIndex = 10;
            LargeImageDomainUpDown.Text = "Album [Default]";
            LargeImageDomainUpDown.Wrap = true;
            SmallImageDomainUpDown.Items.Add("Track");
            SmallImageDomainUpDown.Items.Add("Artist [Default]");
            SmallImageDomainUpDown.Items.Add("Album");
            SmallImageDomainUpDown.Location = new Point(109, 94);
            SmallImageDomainUpDown.Name = "SmallImageDomainUpDown";
            SmallImageDomainUpDown.ReadOnly = true;
            SmallImageDomainUpDown.Size = new Size(120, 23);
            SmallImageDomainUpDown.TabIndex = 9;
            SmallImageDomainUpDown.Text = "Artist [Default]";
            SmallImageDomainUpDown.Wrap = true;
            LargeImageLabel.AutoSize = true;
            LargeImageLabel.Location = new Point(243, 96);
            LargeImageLabel.Name = "LargeImageLabel";
            LargeImageLabel.Size = new Size(72, 15);
            LargeImageLabel.TabIndex = 8;
            LargeImageLabel.Text = "Large image";
            SmallImageLabel.AutoSize = true;
            SmallImageLabel.Location = new Point(18, 94);
            SmallImageLabel.Name = "SmallImageLabel";
            SmallImageLabel.Size = new Size(72, 15);
            SmallImageLabel.TabIndex = 7;
            SmallImageLabel.Text = "Small image";
            ChangeSettingsButton.Location = new Point(436, 123);
            ChangeSettingsButton.Name = "ChangeSettingsButton";
            ChangeSettingsButton.Size = new Size(72, 23);
            ChangeSettingsButton.TabIndex = 6;
            ChangeSettingsButton.Text = "Change";
            ChangeSettingsButton.UseVisualStyleBackColor = true;
            ChangeSettingsButton.Click += ChangeSettingsButton_Click;
            DetailsFormatTextBox.Location = new Point(243, 59);
            DetailsFormatTextBox.MaxLength = 100;
            DetailsFormatTextBox.Name = "DetailsFormatTextBox";
            DetailsFormatTextBox.PlaceholderText = "'{Track}' - '{Artist}'";
            DetailsFormatTextBox.Size = new Size(265, 23);
            DetailsFormatTextBox.TabIndex = 5;
            DetailsFormatLinkLabel.AutoSize = true;
            DetailsFormatLinkLabel.Location = new Point(243, 33);
            DetailsFormatLinkLabel.Name = "DetailsFormatLinkLabel";
            DetailsFormatLinkLabel.Size = new Size(81, 15);
            DetailsFormatLinkLabel.TabIndex = 4;
            DetailsFormatLinkLabel.TabStop = true;
            DetailsFormatLinkLabel.Text = "Details format";
            DetailsFormatLinkLabel.LinkClicked += DetailsFormatLinkLabel_LinkClicked;
            SecondButtonDomainUpDown.Items.Add("Yandex Music");
            SecondButtonDomainUpDown.Items.Add("Track");
            SecondButtonDomainUpDown.Items.Add("Artist [Default]");
            SecondButtonDomainUpDown.Items.Add("Album");
            SecondButtonDomainUpDown.Location = new Point(109, 59);
            SecondButtonDomainUpDown.Name = "SecondButtonDomainUpDown";
            SecondButtonDomainUpDown.ReadOnly = true;
            SecondButtonDomainUpDown.Size = new Size(120, 23);
            SecondButtonDomainUpDown.TabIndex = 3;
            SecondButtonDomainUpDown.Text = "Artist [Default]";
            SecondButtonDomainUpDown.Wrap = true;
            SecondButtonLabel.AutoSize = true;
            SecondButtonLabel.Location = new Point(18, 61);
            SecondButtonLabel.Name = "SecondButtonLabel";
            SecondButtonLabel.Size = new Size(85, 15);
            SecondButtonLabel.TabIndex = 2;
            SecondButtonLabel.Text = "Second button";
            FirstButtonDomainUpDown.Items.Add("Yandex Music");
            FirstButtonDomainUpDown.Items.Add("Track [Default]");
            FirstButtonDomainUpDown.Items.Add("Artist");
            FirstButtonDomainUpDown.Items.Add("Album");
            FirstButtonDomainUpDown.Location = new Point(92, 31);
            FirstButtonDomainUpDown.Name = "FirstButtonDomainUpDown";
            FirstButtonDomainUpDown.ReadOnly = true;
            FirstButtonDomainUpDown.Size = new Size(120, 23);
            FirstButtonDomainUpDown.TabIndex = 1;
            FirstButtonDomainUpDown.Text = "Track [Default]";
            FirstButtonDomainUpDown.Wrap = true;
            FirstButtonLabel.AutoSize = true;
            FirstButtonLabel.Location = new Point(18, 33);
            FirstButtonLabel.Name = "FirstButtonLabel";
            FirstButtonLabel.Size = new Size(68, 15);
            FirstButtonLabel.TabIndex = 0;
            FirstButtonLabel.Text = "First button";
            RPCCheckBox.AutoSize = true;
            RPCCheckBox.Checked = true;
            RPCCheckBox.CheckState = CheckState.Checked;
            RPCCheckBox.Location = new Point(205, 15);
            RPCCheckBox.Name = "RPCCheckBox";
            RPCCheckBox.Size = new Size(142, 19);
            RPCCheckBox.TabIndex = 1;
            RPCCheckBox.Text = "Discord Rich Presence";
            RPCCheckBox.UseVisualStyleBackColor = true;
            RPCCheckBox.CheckedChanged += RPCCheckBox_CheckedChanged;
            DarkThemeCheckBox.AutoSize = true;
            DarkThemeCheckBox.Location = new Point(353, 15);
            DarkThemeCheckBox.Name = "DarkThemeCheckBox";
            DarkThemeCheckBox.Size = new Size(89, 19);
            DarkThemeCheckBox.TabIndex = 2;
            DarkThemeCheckBox.Text = "Dark Theme";
            DarkThemeCheckBox.UseVisualStyleBackColor = true;
            DarkThemeCheckBox.CheckedChanged += DarkThemeCheckBox_CheckedChanged;
            CaptionColorButton.Location = new Point(12, 12);
            CaptionColorButton.Name = "CaptionColorButton";
            CaptionColorButton.Size = new Size(187, 23);
            CaptionColorButton.TabIndex = 3;
            CaptionColorButton.Text = "Change window caption color";
            CaptionColorButton.UseVisualStyleBackColor = true;
            CaptionColorButton.Click += CaptionColorButton_Click;
            CaptionColorDialog.AnyColor = true;
            CaptionColorDialog.Color = SystemColors.Control;
            CaptionColorDialog.FullOpen = true;
            AutoStartCheckBox.AutoSize = true;
            AutoStartCheckBox.Location = new Point(448, 15);
            AutoStartCheckBox.Name = "AutoStartCheckBox";
            AutoStartCheckBox.Size = new Size(78, 19);
            AutoStartCheckBox.TabIndex = 4;
            AutoStartCheckBox.Text = "Auto start";
            AutoStartCheckBox.UseVisualStyleBackColor = true;
            AutoStartCheckBox.CheckedChanged += AutoStartCheckBox_CheckedChanged;
            SourceCodeLinkLabel.AutoSize = true;
            SourceCodeLinkLabel.Location = new Point(12, 41);
            SourceCodeLinkLabel.Name = "SourceCodeLinkLabel";
            SourceCodeLinkLabel.Size = new Size(74, 15);
            SourceCodeLinkLabel.TabIndex = 5;
            SourceCodeLinkLabel.TabStop = true;
            SourceCodeLinkLabel.Text = "Source Code";
            SourceCodeLinkLabel.LinkClicked += SourceCodeLinkLabel_LinkClicked;
            HideToTrayButton.Location = new Point(403, 40);
            HideToTrayButton.Name = "HideToTrayButton";
            HideToTrayButton.Size = new Size(117, 23);
            HideToTrayButton.TabIndex = 6;
            HideToTrayButton.Text = "Hide to tray";
            HideToTrayButton.UseVisualStyleBackColor = true;
            HideToTrayButton.Click += HideToTrayButton_Click;
            TrayIcon.ContextMenuStrip = TrayContextMenu;
            TrayIcon.Icon = (Icon)resources.GetObject("TrayIcon.Icon");
            TrayIcon.Text = "Yandex Music Discord RPC";
            TrayContextMenu.Items.AddRange(new ToolStripItem[] { openToolStripMenuItem, exitToolStripMenuItem });
            TrayContextMenu.Name = "TrayContextMenu";
            TrayContextMenu.Size = new Size(104, 48);
            openToolStripMenuItem.Name = "openToolStripMenuItem";
            openToolStripMenuItem.Size = new Size(103, 22);
            openToolStripMenuItem.Text = "Open";
            openToolStripMenuItem.Click += openToolStripMenuItem_Click;
            exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            exitToolStripMenuItem.Size = new Size(103, 22);
            exitToolStripMenuItem.Text = "Exit";
            exitToolStripMenuItem.Click += exitToolStripMenuItem_Click;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(531, 220);
            Controls.Add(HideToTrayButton);
            Controls.Add(SourceCodeLinkLabel);
            Controls.Add(AutoStartCheckBox);
            Controls.Add(CaptionColorButton);
            Controls.Add(DarkThemeCheckBox);
            Controls.Add(RPCCheckBox);
            Controls.Add(SettingsGroup);
            FormBorderStyle = FormBorderStyle.FixedDialog;
            Icon = (Icon)resources.GetObject("$this.Icon");
            MaximizeBox = false;
            Name = "MainWindow";
            Text = "Yandex Music Discord RPC manager";
            FormClosing += MainWindow_FormClosing;
            SettingsGroup.ResumeLayout(false);
            SettingsGroup.PerformLayout();
            TrayContextMenu.ResumeLayout(false);
            ResumeLayout(false);
            PerformLayout();
        }
        private GroupBox SettingsGroup;
        private CheckBox RPCCheckBox;
        private CheckBox DarkThemeCheckBox;
        private Button CaptionColorButton;
        private ColorDialog CaptionColorDialog;
        private CheckBox AutoStartCheckBox;
        private Label FirstButtonLabel;
        private DomainUpDown SecondButtonDomainUpDown;
        private Label SecondButtonLabel;
        private DomainUpDown FirstButtonDomainUpDown;
        private LinkLabel DetailsFormatLinkLabel;
        private TextBox DetailsFormatTextBox;
        private Button ChangeSettingsButton;
        private DomainUpDown SmallImageDomainUpDown;
        private Label LargeImageLabel;
        private Label SmallImageLabel;
        private DomainUpDown LargeImageDomainUpDown;
        private LinkLabel SourceCodeLinkLabel;
        private Button HideToTrayButton;
        private NotifyIcon TrayIcon;
        private ContextMenuStrip TrayContextMenu;
        private ToolStripMenuItem openToolStripMenuItem;
        private ToolStripMenuItem exitToolStripMenuItem;
    }
}